CREATE TABLE questions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  level INT NOT NULL,
  question VARCHAR(255) NOT NULL,
  answer VARCHAR(255) NOT NULL,
  details VARCHAR(255)
);

CREATE TABLE choices (
  id INT PRIMARY KEY AUTO_INCREMENT,
  question_id INT NOT NULL,
  choice_1 VARCHAR(255) NOT NULL,
  choice_2 VARCHAR(255) NOT NULL,
  choice_3 VARCHAR(255),
  choice_4 VARCHAR(255),
  FOREIGN KEY (question_id) REFERENCES questions(id)
);

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);